
executable = EXECUTABLES/options_train.sh
arguments  = $(n_ensemble) $(batch_size) $(n_epochs) $(patience) $(lr) $(weight_decay) $(Cluster)_$(Process)

log    = LOG_FILES/options_train_$(Cluster)_$(Process).log
error  = ERROR_FILES/options_train_$(Cluster)_$(Process).err
output = OUTPUT_FILES/options_train_$(Cluster)_$(Process).out

notify_user  = s.singh.3@research.gla.ac.uk
notification = Error
getenv       = True

request_GPUs   = 1
request_cpus   = 1
request_memory = 16GB

queue n_ensemble,batch_size,n_epochs,patience,lr,weight_decay from (
    5           2048        300      30       3.0e-4  1.0e-5
    5           2048        300      30       1.0e-4  1.0e-5
    3           2048        300      30       3.0e-4  1.0e-5
    7           2048        300      30       3.0e-4  1.0e-5
    5           1024        300      30       3.0e-4  1.0e-5
    5           2048        300      30       3.0e-4  1.0e-4
)