
executable = EXECUTABLES/SchwartzSmithFWD_training.sh
arguments  = $(batch_size) $(alpha) $(beta) $(n_epochs) $(patience) $(lr) $(weight_decay) $(Cluster)_$(Process)

log    = LOG_FILES/train_SchwartzSmithFWD_$(Cluster)_$(Process).log
error  = ERROR_FILES/train_SchwartzSmithFWD_$(Cluster)_$(Process).err
output = OUTPUT_FILES/train_SchwartzSmithFWD_$(Cluster)_$(Process).out

notify_user  = s.singh.3@research.gla.ac.uk
notification = Error
getenv       = True

request_GPUs   = 1
request_cpus   = 1
request_memory = 12GB

queue batch_size,alpha,beta,n_epochs,patience,lr,weight_decay from (
    2048        0.10  0.10 600      40       3.0e-4   1.0e-5
    2048        0.05  0.05 600      40       3.0e-4   1.0e-5
    2048        0.20  0.20 600      40       3.0e-4   1.0e-5
    1024        0.10  0.10 600      40       3.0e-4   1.0e-5
    4096        0.10  0.10 600      40       3.0e-4   1.0e-5
    2048        0.10  0.10 600      40       1.0e-4   1.0e-5
    2048        0.10  0.10 600      40       3.0e-4   1.0e-4
)